name: saegim
description: "SaeGim"
publish_to: "none"
version: 0.1.6

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  logger: ^2.6.1
  fl_chart: ^0.68.0
  dio: ^5.9.0
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  crypto: ^3.0.3
  image_picker: ^1.0.7
  http: ^1.2.2
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  shared_preferences: ^2.3.3
  package_info_plus: ^8.0.2
  device_info_plus: ^11.1.0
  flutter_local_notifications: ^17.2.2
  google_sign_in: ^6.2.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/env/.env
    - assets/emoji/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#f5f5f5" # 기존 로고의 배경색과 유사한 색상
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true # iOS App Store 제출을 위한 알파 채널 제거
